### ISSUE TITLE
无法调用

### ISSUE THREAD

**Issue by duchao1990** [qiqizjl/think-wechat#9]
[0] ClassNotFoundException in Container.php line 442
类不存在: wechat.mini_program

tp版本:5.1.29

**Comment by duchao1990** [comment]
`            $config=[
                'app_id'  => env('WECHAT_MINI_PROGRAM_APPID', $app_id),
                'secret'  => env('WECHAT_MINI_PROGRAM_SECRET', $secret),
                'token'   => env('WECHAT_MINI_PROGRAM_TOKEN', $token),
                'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', $aes_key),
            ];
            $this->app= Facade::miniProgram('',$config);`

**Comment by duchao1990** [comment]
`
            $config=[
                'app_id'  => env('WECHAT_MINI_PROGRAM_APPID', $app_id),

                'secret'  => env('WECHAT_MINI_PROGRAM_SECRET', $secret),

                'token'   => env('WECHAT_MINI_PROGRAM_TOKEN', $token),

                'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', $aes_key),
            ];

            $this->app= Facade::miniProgram('',$config);
`

**Comment by duchao1990** [comment]
` $config=[`
               ` 'app_id'  => env('WECHAT_MINI_PROGRAM_APPID', $app_id),`
                `'secret'  => env('WECHAT_MINI_PROGRAM_SECRET', $secret),`
                `'token'   => env('WECHAT_MINI_PROGRAM_TOKEN', $token),`
               ` 'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', $aes_key),`
            `];`
`            $this->app= Facade::miniProgram('',$config);`

**Comment by qiqizjl** [comment]
尝试在config中，把小程序的配置注释掉，看是否可以调用？




    
    
        
        
            
                
                    耐小心
                    
                    
                                
                                    qiqizjl@qq.com
                                
                
            
        
        
    

签名由 网易邮箱大师 定制


在2018年12月08日 12:06，onejfs 写道：  $config=[
 'app_id'  => env('WECHAT_MINI_PROGRAM_APPID', $app_id),
'secret'  => env('WECHAT_MINI_PROGRAM_SECRET', $secret),
'token'   => env('WECHAT_MINI_PROGRAM_TOKEN', $token),
 'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', $aes_key),
];
            $this->app= Facade::miniProgram('',$config);

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qiqizjl/think-wechat","title":"qiqizjl/think-wechat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/qiqizjl/think-wechat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@duchao1990 in #9: ` $config=[`\r\n               ` 'app_id'  =\u003e env('WECHAT_MINI_PROGRAM_APPID', $app_id),`\r\n                `'secret'  =\u003e env('WECHAT_MINI_PROGRAM_SECRET', $secret),`\r\n                `'token'   =\u003e env('WECHAT_MINI_PROGRAM_TOKEN', $token),`\r\n               ` 'aes_key' =\u003e env('WECHAT_MINI_PROGRAM_AES_KEY', $aes_key),`\r\n            `];`\r\n`            $this-\u003eapp= Facade::miniProgram('',$config);`"}],"action":{"name":"View Issue","url":"https://github.com/qiqizjl/think-wechat/issues/9#issuecomment-445428598"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qiqizjl/think-wechat/issues/9#issuecomment-445428598",
"url": "https://github.com/qiqizjl/think-wechat/issues/9#issuecomment-445428598",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [qiqizjl/think-wechat] 无法调用 (#9)",
"sections": [
{
"text": "",
"activityTitle": "**onejfs**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@duchao1990",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"qiqizjl/think-wechat\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"qiqizjl/think-wechat\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/qiqizjl/think-wechat/issues/9#issuecomment-445428598"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 421906260\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by duchao1990** [comment]
![image](https://user-images.githubusercontent.com/9289694/49681981-04844700-fae6-11e8-8f29-f2c6d8c211f8.png)
这个注释都是注销掉的

**Comment by qiqizjl** [comment]
将mini_program取消注释

**Comment by duchao1990** [comment]
Array
(
    [app_id] => 我的app_id
    [secret] => 我的密钥
    [token] => 
    [aes_key] => 
)
`{"code":1,"msg":"Request access_token fail: {\"errcode\":41002,\"errmsg\":\"appid missing hint: [1knegA0963b101]\"}","time":1544492965,"data":false}`

**Comment by duchao1990** [comment]
注释已经取消了

**Comment by qiqizjl** [comment]
我这边将mini_program取消注释之后 是可以调用的。检查你的Appid之类的是否正确
![image](https://user-images.githubusercontent.com/7540584/49775337-cfb8ff80-fd32-11e8-9e42-ee89330bed24.png)
![image](https://user-images.githubusercontent.com/7540584/49775349-d9dafe00-fd32-11e8-8ce4-7afbdf726ca0.png)

**Comment by duchao1990** [comment]
我用easywechat是可以用的

**Comment by qiqizjl** [comment]
方便把wechat.php脱敏之后发个我么~ 还有业务侧简单复现的demo

**Comment by duchao1990** [comment]
![image](https://user-images.githubusercontent.com/9289694/49775578-9d5bd200-fd33-11e8-840b-b5c9bed77984.png)
这个是我现在使用的是不是token和aes_key问题,但是这个两个参数好像并不是必须的

**Comment by qiqizjl** [comment]
检查下appid 是否有传入？

**Comment by qiqizjl** [comment]
![image](https://user-images.githubusercontent.com/7540584/49775804-5de1b580-fd34-11e8-838b-38f27b545474.png)
第一个参数是账号名称，第二个才是参数 尝试``miniProgram('',$config)``呢

**Comment by duchao1990** [comment]
`$this->app= Facade::miniProgram('',$config);`
是第二个参数啊

**Comment by qiqizjl** [comment]
第二个参数也不行？ 检查下appid是否存在

**Comment by duchao1990** [comment]
肯定存在的呀,要不是调用easywechat也不能用啊,关键easywechat能用
![image](https://user-images.githubusercontent.com/9289694/49776457-14df3080-fd37-11e8-9d03-4b707849f40b.png)

Array
(
    [app_id] => wxb4d236c7d768fbbd
    [secret] => 109252133fcaaad5c4f580ea******
    [token] => 
    [aes_key] => 
)
{"code":1,"msg":"Request access_token fail: {\"errcode\":41002,\"errmsg\":\"appid missing hint: [JwOIiA05141501]\"}","time":1544498516,"data":false}

**Comment by qiqizjl** [comment]
应该是个bug 我这边查看下~

**Comment by qiqizjl** [comment]
@duchao1990 已经在Master Fix了 可直接用dev-master测试下~

**Comment by qiqizjl** [comment]
已经发布到1.4.0 更新下think-wechat这个包即可

**Comment by duchao1990** [comment]
小哥,关闭的有点早了,我这边如果是nginx和php-fpm用着没问题 如果用swoole或者workerman 作为http服务器启动的话,这个sdk是无法使用的,错误就是上边这个错误   wechat.mini_program  你可以使用think-worker 或者think-swoole测试一下,

**Comment by qiqizjl** [comment]
好的 你用的是swoole的组件是么还是workman

**Comment by duchao1990** [comment]
我用的workman的http服务,然后使用nginx做的代理

**Comment by qiqizjl** [comment]
hi 目前看起来是命令行启动的时候未加载我的文件 我会尽快解决

**Comment by qiqizjl** [comment]
hi 
尝试在app/tags.php中 app_init增加我的行为扩展
``` php

    'app_init'     => [
        \Naixiaoxin\ThinkWechat\Behavior\AppInit::class
    ],

```
